Name: user.rpc
ListenOn: 0.0.0.0:9000
Etcd:
  Hosts:
  - etcd:2379
  Key: user.rpc


Mysql:
  DataSource: root:123456@tcp(mysql:3306)/mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
- Host: redis:6379
  Type: node


# IP 会变化，但容器名固定不变，一一映射即可。 

Salt: HWVOFkGgPTryzICwd7qnJaZR9KQ2i8xe